In [17]:
from typing import List

import nltk
from nltk import pos_tag_sents, sent_tokenize, word_tokenize
from nltk.stem.wordnet import WordNetLemmatizer
from pygments.lexer import words
from nltk.corpus import wordnet

nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/qr/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [45]:
from typing import Tuple


def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN  # Default to noun


text = "Python programmers often tend like programming sdgfgsdfg in python because it's like english. We call people who program in python pythonistas"

sentences = sent_tokenize(text)
tokens = [word_tokenize(sent) for sent in sentences]
positions: List[List[Tuple[str, str]]] = pos_tag_sents(words)

lemma = WordNetLemmatizer()
lemma_words = [
    lemma.lemmatize(word, get_wordnet_pos(pos)).lower()
    for sent in positions
    for word, pos in sent
    if wordnet.synsets(word)
]

print(text)
# print(sentences)
# print(words)
# print(positions)
print(" ".join(lemma_words))

Python programmers often tend like programming sdgfgsdfg in python because it's like english. We call people who program in python pythonistas
python programmer often tend like program in python it like english call people who program in python

In [8]:
import polars as pl

ai_type = pl.Enum(["AI", "UNKNOWN", "HUMAN"])
blacklist = [
    "Please wait while your request is being verified...",
    "AI scrapers break the web, to use this page you'll need JavaScript enabled.",
    "Javascript is required for this site. Consider enabling Javascript or upgrading to a modern browser.",
    "This domain name registration has expired and renewal or deletion are pending. If you are the registrant and "
    "want to renew the domain name, please contact your registration service provider.",
    "We're sorry but doesn't work properly without JavaScript enabled. Please enable it to continue.",
    "This page was generated on 20"
]

(
    pl
    .read_parquet("/mnt/Fast2T/data/stage_4/CC-MAIN-20260206181458-20260206211458-00190.parquet")
    .filter(pl.col("lang_en") > 0.7)
    .filter(pl.col("text").str.len_bytes() > 200)
    .filter(~pl.col("text").str.contains_any(blacklist))
    .with_columns(
        pl
        .when(pl.col('ai') < 0.005).then(pl.lit("HUMAN"))
        .when(pl.col('ai') > 0.9).then(pl.lit("AI"))
        .otherwise(pl.lit("UNKNOWN"))
        .cast(ai_type).alias("is_ai"),
    )
    .with_columns(
        pl
        .col("outflow")
        .map_elements(
            lambda s: [{ "url": k, "occurrences": v } for k, v in s.items() if v is not None],
            return_dtype=pl.List(pl.Struct({ "url": pl.String, "occurrences": pl.Int64 })),
        ),
    )
    .select("host", "url", "text", "outflow", "is_ai")
)

shape: (3_984, 5)
┌──────────────────────┬─────────────────────┬─────────────────────┬─────────────────────┬─────────┐
│ host                 ┆ url                 ┆ text                ┆ outflow             ┆ is_ai   │
│ ---                  ┆ ---                 ┆ ---                 ┆ ---                 ┆ ---     │
│ str                  ┆ str                 ┆ str                 ┆ list[struct[2]]     ┆ enum    │
╞══════════════════════╪═════════════════════╪═════════════════════╪═════════════════════╪═════════╡
│ 03-128-53-208.plesk. ┆ http://03-128-53-20 ┆ Day Two Draft       ┆ [{"03-128-53-208.pl ┆ HUMAN   │
│ page                 ┆ 8.plesk.pag…        ┆ Recap: Cubs Add …   ┆ esk.page",4…        ┆         │
│ 550squadronassociati ┆ http://550squadrona ┆ Listed below is the ┆ [{"550squadronassoc ┆ UNKNOWN │
│ on.org.uk            ┆ ssociation.…        ┆ informatio…         ┆ iation.org.…        ┆         │
│ allmedschools.com    ┆ http://allmedschool ┆ AMCAS application   ┆ [{"wordpress.org",1 ┆ HUMAN   │
│                      ┆ s.com/unive…        ┆ accepted? Ye…       ┆ }, {"allmed…        ┆         │
│ anarchy2023.org      ┆ http://anarchy2023. ┆ Bookfair/Exposition ┆ [{"anarchy2023.org" ┆ HUMAN   │
│                      ┆ org/en/book…        ┆ You can ge…         ┆ ,39}]               ┆         │
│ arahn.100webspace.ne ┆ http://arahn.100web ┆ ARAHN               ┆ [{"arahn.100webspac ┆ HUMAN   │
│ t                    ┆ space.net/s…        ┆ A_R_A_H_N           ┆ e.net",10},…        ┆         │
│                      ┆                     ┆ FAQ                 ┆                     ┆         │
│                      ┆                     ┆ Search              ┆                     ┆         │
│                      ┆                     ┆ Mem…                ┆                     ┆         │
│ …                    ┆ …                   ┆ …                   ┆ …                   ┆ …       │
│ zarzarfashion.com    ┆ https://zarzarfashi ┆ What It Is: An      ┆ [{"www.facebook.com ┆ HUMAN   │
│                      ┆ on.com/prod…        ┆ anti-aging faci…    ┆ ",1}, {"www…        ┆         │
│ zecatech.com         ┆ https://zecatech.co ┆ On the other hand,  ┆ []                  ┆ UNKNOWN │
│                      ┆ m/project/e…        ┆ we denounce…        ┆                     ┆         │
│ zenerva.com          ┆ https://zenerva.com ┆ Designers lose      ┆ [{"www.facebook.com ┆ HUMAN   │
│                      ┆ /app-reskin…        ┆ time, cash, and…    ┆ ",1}, {"twi…        ┆         │
│ zh-hk.wordpress.org  ┆ https://zh-hk.wordp ┆ 描述                ┆ [{"www.facebook.com ┆ HUMAN   │
│                      ┆ ress.org/pl…        ┆ Install Formilla’s  ┆ ",1}, {"www…        ┆         │
│                      ┆                     ┆ Customer…           ┆                     ┆         │
│ zilvera.nl           ┆ https://zilvera.nl/ ┆ Description         ┆ [{"en.wikipedia.org ┆ HUMAN   │
│                      ┆ product/squ…        ┆ Square amethyst fl… ┆ ",1}]               ┆         │
└──────────────────────┴─────────────────────┴─────────────────────┴─────────────────────┴─────────┘

In [5]:
import polars as pl

(
    pl
    .scan_parquet("/mnt/Fast2T/data/stage_4/*.parquet")
    .select("text")
    .with_columns(abfff=(pl.col("text").str.len_bytes() / 100.0).cast(pl.Int64))
    .group_by("abfff")
    .len()
    .collect()
)

shape: (7_086, 2)
┌───────┬─────┐
│ abfff ┆ len │
│ ---   ┆ --- │
│ i64   ┆ u32 │
╞═══════╪═════╡
│ 3671  ┆ 1   │
│ 38678 ┆ 2   │
│ 8914  ┆ 3   │
│ 4594  ┆ 2   │
│ 1447  ┆ 13  │
│ …     ┆ …   │
│ 7988  ┆ 1   │
│ 914   ┆ 114 │
│ 780   ┆ 77  │
│ 655   ┆ 193 │
│ 2620  ┆ 4   │
└───────┴─────┘